// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNj9EHU3VybYQrkqzOqLgOmYB8_nGQMk0',
    appId: '1:973264485339:web:9f099cdef9eaa51e6745fe',
    messagingSenderId: '973264485339',
    projectId: 'wallet-74af0',
    authDomain: 'wallet-74af0.firebaseapp.com',
    databaseURL: 'https://wallet-74af0-default-rtdb.firebaseio.com',
    storageBucket: 'wallet-74af0.appspot.com',
    measurementId: 'G-9RXB13N8D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB71Kw4C0NLCjHr5D-oq7PPHKTfuTIXIR4',
    appId: '1:973264485339:android:a7e39e151a9418766745fe',
    messagingSenderId: '973264485339',
    projectId: 'wallet-74af0',
    databaseURL: 'https://wallet-74af0-default-rtdb.firebaseio.com',
    storageBucket: 'wallet-74af0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdSXr3ketUXgbSnheJuQuk3bZ2vbsvE2k',
    appId: '1:973264485339:ios:aa2c122f0b51b0696745fe',
    messagingSenderId: '973264485339',
    projectId: 'wallet-74af0',
    databaseURL: 'https://wallet-74af0-default-rtdb.firebaseio.com',
    storageBucket: 'wallet-74af0.appspot.com',
    iosClientId: '973264485339-cbni40fc6aijums1g6jpot490ls3j9l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdSXr3ketUXgbSnheJuQuk3bZ2vbsvE2k',
    appId: '1:973264485339:ios:5620d43988c197106745fe',
    messagingSenderId: '973264485339',
    projectId: 'wallet-74af0',
    databaseURL: 'https://wallet-74af0-default-rtdb.firebaseio.com',
    storageBucket: 'wallet-74af0.appspot.com',
    iosClientId: '973264485339-v2p3vb6u4du7bkii9egg2ihqc2s9oe9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallet.RunnerTests',
  );
}
